import { Client, GatewayIntentBits, Partials } from 'discord.js';
import { createServer } from 'node:http';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { randomBytes, randomUUID } from 'node:crypto';
import { join, resolve } from 'node:path';

try { const text = await readFile(resolve(process.cwd(), '.env'), 'utf8'); for (const line of text.split(/\r?\n/)) { const item = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/); if (item && process.env[item[1]] === undefined) process.env[item[1]] = item[2].replace(/^['"]|['"]$/g, ''); } } catch { /* .env is optional */ }
const config = { token: process.env.DISCORD_BOT_TOKEN, port: Number(process.env.PORT || 3000), pairingTtl: Number(process.env.PAIRING_TTL_MINUTES || 15) * 60_000, sessionTtl: Number(process.env.MOBILE_SESSION_TTL_MINUTES || 10) * 60_000 };
if (!config.token) throw new Error('DISCORD_BOT_TOKEN を設定してください');
const dir = resolve(process.cwd(), 'relay-data'), file = join(dir, 'state.json'); await mkdir(dir, { recursive: true });
let state = { devices: {}, pairings: {}, sessions: {}, receipts: {} }; try { state = { ...state, ...JSON.parse(await readFile(file, 'utf8')) }; } catch { /* first boot */ }
let saving = Promise.resolve(); const save = () => saving = saving.catch(() => {}).then(() => writeFile(file, JSON.stringify(state, null, 2), 'utf8'));
const secret = (size = 24) => randomBytes(size).toString('base64url'); const code = () => randomBytes(6).toString('hex').toUpperCase(); const image = item => /^image\//.test(item.contentType || '') || /\.(jpe?g|png|webp|gif)$/i.test(item.name || '');
const json = (res, status, body) => { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(body)); };
function body(req) { return new Promise((resolveBody, reject) => { let value = ''; req.on('data', part => { value += part; if (value.length > 1_000_000) req.destroy(); }); req.on('end', () => { try { resolveBody(value ? JSON.parse(value) : {}); } catch { reject(new Error('JSON形式が不正です')); } }); req.on('error', reject); }); }
function device(req) { const key = (req.headers.authorization || '').match(/^Bearer\s+(.+)$/i)?.[1]; return Object.values(state.devices).find(item => item.token === key); }
function cleanup() { const time = Date.now(); for (const [id, item] of Object.entries(state.pairings)) if (item.expiresAt < time || item.claimedAt) delete state.pairings[id]; for (const [id, item] of Object.entries(state.sessions)) if (item.expiresAt < time) delete state.sessions[id]; }
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent], partials: [Partials.Channel] });
client.once('ready', () => console.log(`OISO Common Relay: ${client.user.tag}`));
client.on('messageCreate', async message => {
  const command = message.content?.trim().match(/^!oiso-pair\s+([A-F0-9]{12})$/i);
  if (!message.author.bot && command) { const pair = state.pairings[command[1].toUpperCase()]; const target = pair && state.devices[pair.deviceId]; if (!pair || pair.expiresAt < Date.now() || !target) return message.reply('コードが無効、または期限切れです。'); target.guildId = message.guildId; target.channelId = message.channelId; target.pairedAt = new Date().toISOString(); pair.pairedAt = Date.now(); await save(); await message.reply('OISO2 PCとの接続が完了しました。'); return message.delete().catch(() => {}); }
  if (!message.webhookId || !message.attachments.size) return;
  const session = Object.values(state.sessions).find(item => item.webhookId === message.webhookId && item.expiresAt > Date.now()); const target = session && state.devices[session.deviceId]; if (!target || target.channelId !== message.channelId) return;
  for (const attachment of [...message.attachments.values()].filter(image).filter(item => item.size <= 20 * 1024 * 1024)) { const id = `R-${randomUUID().slice(0, 8).toUpperCase()}`; state.receipts[id] = { id, deviceId: target.id, messageId: message.id, channelId: message.channelId, name: attachment.name || 'receipt.jpg', size: attachment.size, attachmentUrl: attachment.url, receivedAt: new Date().toISOString() }; }
  await save();
});
await client.login(config.token);
async function mobileSession(target) { const channel = await client.channels.fetch(target.channelId); if (!channel?.createWebhook) throw new Error('BotにWebhook管理権限がありません'); const id = `S-${randomUUID().slice(0, 8).toUpperCase()}`, webhook = await channel.createWebhook({ name: `OISO-${id}` }), expiresAt = Date.now() + config.sessionTtl; state.sessions[id] = { id, deviceId: target.id, webhookId: webhook.id, expiresAt }; await save(); setTimeout(() => webhook.delete('OISO session expired').catch(() => {}), config.sessionTtl + 1000).unref(); return { format: 'oiso-relay', version: 2, sessionId: id, uploadUrl: webhook.url, expiresAt }; }
async function acknowledge(target, ids) { for (const id of ids) { const item = state.receipts[id]; if (!item || item.deviceId !== target.id) continue; const channel = await client.channels.fetch(item.channelId).catch(() => null); const message = await channel?.messages?.fetch(item.messageId).catch(() => null); await message?.delete().catch(() => {}); delete state.receipts[id]; } await save(); }
const server = createServer(async (req, res) => { try { cleanup(); const url = new URL(req.url, `http://${req.headers.host}`); if (req.method === 'GET' && url.pathname === '/health') return json(res, 200, { ok: true, discord: client.isReady(), service: 'oiso-common-relay' }); if (req.method === 'POST' && url.pathname === '/api/pairings') { const id = randomUUID(), value = code(), claimToken = secret(); state.devices[id] = { id, token: secret(), createdAt: new Date().toISOString() }; state.pairings[value] = { deviceId: id, claimToken, expiresAt: Date.now() + config.pairingTtl }; await save(); return json(res, 201, { code: value, claimToken, expiresAt: state.pairings[value].expiresAt }); } if (req.method === 'GET' && url.pathname === '/api/pairings/claim') { const pair = state.pairings[url.searchParams.get('code')?.toUpperCase()], target = pair && state.devices[pair.deviceId]; if (!pair || pair.expiresAt < Date.now()) return json(res, 404, { error: 'ペアリングコードが無効です' }); if (url.searchParams.get('claimToken') !== pair.claimToken) return json(res, 403, { error: 'このPCから開始したペアリングではありません' }); if (!target?.channelId) return json(res, 202, { paired: false }); pair.claimedAt = Date.now(); await save(); return json(res, 200, { paired: true, deviceToken: target.token, channelId: target.channelId }); } const target = device(req); if (!target) return json(res, 401, { error: 'PC Bridgeをペアリングしてください' }); if (req.method === 'POST' && url.pathname === '/api/mobile-sessions') return json(res, 201, await mobileSession(target)); if (req.method === 'GET' && url.pathname === '/api/inbox') return json(res, 200, { receipts: Object.values(state.receipts).filter(item => item.deviceId === target.id).sort((a, b) => a.receivedAt.localeCompare(b.receivedAt)) }); if (req.method === 'POST' && url.pathname === '/api/inbox/ack') { const data = await body(req); await acknowledge(target, Array.isArray(data.ids) ? data.ids : []); return json(res, 200, { ok: true }); } if (req.method === 'POST' && url.pathname === '/api/results') { const data = await body(req), csv = String(data.csv || ''); if (!csv || Buffer.byteLength(csv) > 2_000_000) throw new Error('CSVが空、または大きすぎます'); const channel = await client.channels.fetch(target.channelId); await channel.send({ content: `OISO2解析結果 ${data.jobId || ''}`, files: [{ attachment: Buffer.from(csv), name: data.fileName || 'oiso-result.csv' }] }); return json(res, 200, { ok: true }); } return json(res, 404, { error: 'not found' }); } catch (error) { return json(res, 400, { error: error.message }); } });
server.listen(config.port, '0.0.0.0', () => console.log(`OISO Common Relay listening on ${config.port}`));
