const $=id=>document.getElementById(id),S={r:[],b:[]},bridge={base:'http://127.0.0.1:8788',online:false};const input=$('files'),drop=$('drop'),list=$('list'),count=$('count'),make=$('make'),manifest=$('manifest');const rid=i=>`R-${String(i+1).padStart(3,'0')}`;
const dl=(data,name,type='image/png')=>{const a=document.createElement('a');a.href=typeof data==='string'&&data.startsWith('data:')?data:URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),100)};
const load=file=>new Promise((ok,no)=>{const url=URL.createObjectURL(file),im=new Image();im.onload=()=>ok({im,url,name:file.name});im.onerror=no;im.src=url});
async function add(files){for(const file of [...files].filter(file=>file.type.startsWith('image/'))){try{S.r.push(await load(file))}catch{alert(`${file.name} を読み込めませんでした`)}}S.r.forEach((item,index)=>item.id=rid(index));render()}
function render(){count.textContent=`${S.r.length} 枚`;make.disabled=manifest.disabled=!S.r.length;$('bridge-analyze').disabled=!bridge.online||!S.r.some(item=>item.relayId);list.innerHTML='';S.r.forEach((item,index)=>{const e=document.createElement('article');e.className='tile';e.innerHTML=`<img src="${item.url}" alt="${item.id}"><div><code>${item.id}${item.relayId?' · Bridge':''}</code><button aria-label="削除"><i data-lucide="x"></i></button></div>`;e.querySelector('button').onclick=()=>{URL.revokeObjectURL(item.url);S.r.splice(index,1);S.r.forEach((entry,i)=>entry.id=rid(i));S.b=[];$('batches').innerHTML='';render()};list.append(e)});lucide.createIcons()}
function draw(ctx,im,x,y,w,h){const s=Math.min(w/im.width,h/im.height),iw=im.width*s,ih=im.height*s;ctx.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih)}
function batch(items,n){const c=2,r=Math.ceil(items.length/c),m=42,head=72,w=680,h=950,can=document.createElement('canvas');can.width=c*w+(c+1)*m;can.height=head+r*h+(r+1)*m;const x=can.getContext('2d');x.fillStyle='#f5f8fa';x.fillRect(0,0,can.width,can.height);x.fillStyle='#14213d';x.font='600 25px sans-serif';x.fillText(`OISO2 · ANALYSIS BATCH ${String(n+1).padStart(3,'0')}`,m,45);items.forEach((v,i)=>{const px=m+(i%c)*(w+m),py=head+m+Math.floor(i/c)*(h+m);x.fillStyle='#fff';x.fillRect(px,py,w,h);x.strokeStyle='#c9d8e2';x.lineWidth=3;x.strokeRect(px,py,w,h);x.fillStyle='#1769aa';x.font='700 26px monospace';x.fillText(v.id,px+20,py+38);draw(x,v.im,px+24,py+61,w-48,h-85)});return{id:`batch_${String(n+1).padStart(3,'0')}`,items,url:can.toDataURL()}}
function batches(){S.b=[];const n=+$('per').value;for(let i=0;i<S.r.length;i+=n)S.b.push(batch(S.r.slice(i,i+n),S.b.length));const out=$('batches');out.innerHTML='';S.b.forEach(b=>{const e=document.createElement('article');e.className='batch';e.innerHTML=`<img src="${b.url}" alt="${b.id}"><div><span>${b.id}.png · ${b.items.length}枚</span><a download="${b.id}.png" href="${b.url}">PNGを保存</a></div>`;out.append(e)})}
function renderResults(rows){const out=$('results');out.innerHTML='';rows.forEach(v=>{const r=document.createElement('article');r.className='result';r.innerHTML='<code></code><b></b><span class="hide"></span><span></span><em></em>';[v.receiptId||v.id||'IDなし',v.vendor||'店舗名不明',v.date||'日付不明',v.amount==null?'金額不明':`¥${Number(v.amount).toLocaleString()}`,v.category||v.confidence||'未分類'].forEach((z,i)=>r.children[i].textContent=z);out.append(r)})}
async function bridgeRequest(path,options){const response=await fetch(`${bridge.base}${path}`,options),body=await response.json();if(!response.ok)throw Error(body.error||'Bridgeとの通信に失敗しました');return body}
function bridgeStatus(text,state=''){const status=$('bridge-status');status.textContent=text;status.className=state}
async function checkBridge(){bridgeStatus('確認中…');try{const health=await bridgeRequest('/api/health');bridge.online=true;$('bridge-import').disabled=false;$('bridge-session').disabled=!health.discord;bridgeStatus(health.discord?`Discord接続済み · ${health.analyzer}`:`ローカルのみ · ${health.analyzer}`,'ok');render()}catch{bridge.online=false;$('bridge-import').disabled=true;$('bridge-session').disabled=true;bridgeStatus('Bridge未起動','warn');render()}}
async function createMobileSession(){const button=$('bridge-session');button.disabled=true;button.textContent='QR作成中…';try{const session=await bridgeRequest('/api/mobile-sessions',{method:'POST'}),box=$('bridge-qr');box.hidden=false;box.innerHTML=`<img src="${session.qrDataUrl}" alt="OISO送信設定QR"><p>OISOで読み取ると、このPC専用の送信先が設定されます。<b>${new Date(session.expiresAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</b>まで有効です。</p>`}catch(error){alert(`QRを作成できませんでした: ${error.message}`)}finally{button.disabled=false;button.innerHTML='<i data-lucide="qr-code"></i> スマホ送信用QRを作成';lucide.createIcons()}}
async function importBridgeInbox(){const button=$('bridge-import');button.disabled=true;button.textContent='取り込み中…';try{const {receipts}=await bridgeRequest('/api/inbox');let added=0;for(const receipt of receipts){if(S.r.some(item=>item.relayId===receipt.id))continue;const response=await fetch(`${bridge.base}${receipt.url}`),blob=await response.blob(),item=await load(new File([blob],receipt.fileName,{type:blob.type}));item.relayId=receipt.id;S.r.push(item);added++}S.r.forEach((item,index)=>item.id=rid(index));render();alert(added?`${added}枚をBridge受信箱から追加しました。`:'未取り込みの画像はありません。')}catch(error){alert(`受信箱を取り込めませんでした: ${error.message}`)}finally{button.disabled=false;button.innerHTML='<i data-lucide="inbox"></i> 受信箱を取り込む';lucide.createIcons()}}
async function analyzeWithBridge(){const selected=S.r.filter(item=>item.relayId);if(!selected.length)return;const button=$('bridge-analyze');button.disabled=true;button.textContent='解析中…';try{const result=await bridgeRequest('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected.map(item=>item.relayId)})});renderResults(result.records);dl(`\uFEFF${result.csv}`,`oiso2_${result.jobId}.csv`,'text/csv;charset=utf-8');alert(result.mode==='mock'?'ダミー結果CSVを作成しました。BridgeのANALYZER_MODE=codexで実解析を有効にできます。':'解析結果をCSV化しました。Discordにも返送しました。')}catch(error){alert(`Bridge解析に失敗しました: ${error.message}`)}finally{button.disabled=false;button.innerHTML='<i data-lucide="bot"></i> Bridgeで解析してCSVを返す';lucide.createIcons()}}
input.onchange=e=>{add(e.target.files);e.target.value=''};['dragenter','dragover'].forEach(k=>drop.addEventListener(k,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(k=>drop.addEventListener(k,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>add(e.dataTransfer.files));make.onclick=batches;manifest.onclick=()=>dl(JSON.stringify({format:'oiso2-manifest',receipts:S.r.map(x=>({receiptId:x.id,relayId:x.relayId||null,fileName:x.name,batchId:S.b.find(b=>b.items.includes(x))?.id||null}))},null,2),'oiso2_manifest.json','application/json');$('copy').onclick=async()=>{await navigator.clipboard.writeText($('prompt').textContent);$('copy').textContent='コピーしました'};$('json').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text()),a=Array.isArray(d)?d:d.records;if(!Array.isArray(a))throw Error('JSON配列またはrecords配列が必要です');renderResults(a)}catch(err){alert(`読み込み失敗: ${err.message}`)}finally{e.target.value=''}};$('bridge-check').onclick=checkBridge;$('bridge-session').onclick=createMobileSession;$('bridge-import').onclick=importBridgeInbox;$('bridge-analyze').onclick=analyzeWithBridge;lucide.createIcons();checkBridge();
