const $=id=>document.getElementById(id),S={r:[],b:[]};const input=$('files'),drop=$('drop'),list=$('list'),count=$('count'),make=$('make'),manifest=$('manifest');
const rid=i=>`R-${String(i+1).padStart(3,'0')}`;const dl=(data,name,type='image/png')=>{const a=document.createElement('a');a.href=typeof data==='string'?data:URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();if(typeof data!=='string')setTimeout(()=>URL.revokeObjectURL(a.href),100)};
const load=f=>new Promise((ok,no)=>{const url=URL.createObjectURL(f),im=new Image();im.onload=()=>ok({im,url,name:f.name});im.onerror=no;im.src=url});
async function add(fs){for(const f of [...fs].filter(x=>x.type.startsWith('image/'))){try{S.r.push(await load(f))}catch{alert(`${f.name} を読み込めませんでした`)}}S.r.forEach((x,i)=>x.id=rid(i));render()}
function render(){count.textContent=`${S.r.length} 枚`;make.disabled=manifest.disabled=!S.r.length;list.innerHTML='';S.r.forEach((x,i)=>{const e=document.createElement('article');e.className='tile';e.innerHTML=`<img src="${x.url}" alt="${x.id}"><div><code>${x.id}</code><button aria-label="削除"><i data-lucide="x"></i></button></div>`;e.querySelector('button').onclick=()=>{URL.revokeObjectURL(x.url);S.r.splice(i,1);S.r.forEach((y,j)=>y.id=rid(j));S.b=[];$('batches').innerHTML='';render()};list.append(e)});lucide.createIcons()}
function draw(ctx,im,x,y,w,h){const s=Math.min(w/im.width,h/im.height),iw=im.width*s,ih=im.height*s;ctx.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih)}
function batch(items,n){const c=2,r=Math.ceil(items.length/c),m=42,head=72,w=680,h=950,can=document.createElement('canvas');can.width=c*w+(c+1)*m;can.height=head+r*h+(r+1)*m;const x=can.getContext('2d');x.fillStyle='#f5f8fa';x.fillRect(0,0,can.width,can.height);x.fillStyle='#14213d';x.font='600 25px sans-serif';x.fillText(`OISO2 · ANALYSIS BATCH ${String(n+1).padStart(3,'0')}`,m,45);items.forEach((v,i)=>{const px=m+(i%c)*(w+m),py=head+m+Math.floor(i/c)*(h+m);x.fillStyle='#fff';x.fillRect(px,py,w,h);x.strokeStyle='#c9d8e2';x.lineWidth=3;x.strokeRect(px,py,w,h);x.fillStyle='#1769aa';x.font='700 26px monospace';x.fillText(v.id,px+20,py+38);draw(x,v.im,px+24,py+61,w-48,h-85)});return{id:`batch_${String(n+1).padStart(3,'0')}`,items,url:can.toDataURL()}}
function batches(){S.b=[];const n=+$('per').value;for(let i=0;i<S.r.length;i+=n)S.b.push(batch(S.r.slice(i,i+n),S.b.length));const out=$('batches');out.innerHTML='';S.b.forEach(b=>{const e=document.createElement('article');e.className='batch';e.innerHTML=`<img src="${b.url}" alt="${b.id}"><div><span>${b.id}.png · ${b.items.length}枚</span><a download="${b.id}.png" href="${b.url}">PNGを保存</a></div>`;out.append(e)})}
input.onchange=e=>{add(e.target.files);e.target.value=''};['dragenter','dragover'].forEach(k=>drop.addEventListener(k,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(k=>drop.addEventListener(k,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>add(e.dataTransfer.files));make.onclick=batches;manifest.onclick=()=>dl(JSON.stringify({format:'oiso2-manifest',receipts:S.r.map(x=>({receiptId:x.id,fileName:x.name,batchId:S.b.find(b=>b.items.includes(x))?.id||null}))},null,2),'oiso2_manifest.json','application/json');
$('copy').onclick=async()=>{await navigator.clipboard.writeText($('prompt').textContent);$('copy').textContent='コピーしました'};$('json').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text()),a=Array.isArray(d)?d:d.records;if(!Array.isArray(a))throw Error('JSON配列またはrecords配列が必要です');const out=$('results');out.innerHTML='';a.forEach(v=>{const r=document.createElement('article');r.className='result';r.innerHTML=`<code></code><b></b><span class="hide"></span><span></span><em></em>`;[v.receiptId||v.id||'IDなし',v.vendor||'店舗名不明',v.date||'日付不明',v.amount==null?'金額不明':`¥${Number(v.amount).toLocaleString()}`,v.category||v.confidence||'未分類'].forEach((z,i)=>r.children[i].textContent=z);out.append(r)})}catch(err){alert(`読み込み失敗: ${err.message}`)}finally{e.target.value=''}};lucide.createIcons();
